LOAD DATA 
CHARACTERSET AL32UTF8
APPEND
PRESERVE BLANKS
INTO TABLE TBW_HOGE3
FIELDS TERMINATED BY','
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS
 ( 
cust_no DECIMAL EXTERNAL,
chr_col CHAR (10),
var_col CHAR (10),
hoge CHAR (40)
)
